site_name: F113X
nav:
  - Home: index.md
  - About: about.md

  - Notes:
    - Todo List: Notes/todo.md
    - Design Philosophy 2026: Notes/design-philosophy.md
    - 13-01-2026: Notes/13-01-2026.md
    - 21-01-2026: Notes/21-01-2026.md

  - Eurorack:

    - 2399 Digital Delay Line: 
      - Overview: Eurorack/2399-Digital-Delay-Line/index.md
      - Manual: Eurorack/2399-Digital-Delay-Line/Manual.md
    
    - 4022 Eight Stage Sequencer:
      - Overview: Eurorack/4022-Eight-Stage-Sequencer/index.md
      - Manual: Eurorack/4022-Eight-Stage-Sequencer/Manual.md
    
    - 606 Hihat Generator:
      - Overview: Eurorack/606-Hihat-Generator/index.md
      - Manual: Eurorack/606-Hihat-Generator/Manual.md
    
    - 909 Kick Generator:
      - Overview: Eurorack/909-Kick-Generator/index.md
      - Manual: Eurorack/909-Kick-Generator/Manual.md

    - 201 Dual Attenuverters:
      - Overview: Eurorack/201-Dual-Attenuverters/index.md
      - Manual: Eurorack/201-Dual-Attenuverters/Manual.md
    
    - 202 Passive Signal Multipliers:
      - Overview: Eurorack/202-Passive-Signal-Multipliers/index.md
      - Manual: Eurorack/202-Passive-Signal-Multipliers/Manual.md
    
    - 301 Variable Waveshape LFO:
      - Overview: Eurorack/301-Variable-Waveshape-LFO/index.md
      - Manual: Eurorack/301-Variable-Waveshape-LFO/Manual.md
    
    - 302 Dual Analog Saw Core VCO:
      - Overview: Eurorack/302-Dual-Analog-Saw-Core-VCO/index.md
      - Manual: Eurorack/302-Dual-Analog-Saw-Core-VCO/Manual.md
    
    - 304 Quad Channel Voltage Controlled Mixer:
      - Overview: Eurorack/304-Quad-Channel-Voltage-Controlled-Mixer/index.md
      - Manual: Eurorack/304-Quad-Channel-Voltage-Controlled-Mixer/Manual.md
      
    - 305 Analogue Stochastic Signal Generators:
      - Overview: Eurorack/305-Analogue-Stochastic-Signal-Generators/index.md
      - Manual: Eurorack/305-Analogue-Stochastic-Signal-Generators/Manual.md
    
    - 306 Voltage Controlled Envelope Generator:
      - Overview: Eurorack/306-Voltage-Controlled-Envelope-Generator/index.md
      - Manual: Eurorack/306-Voltage-Controlled-Envelope-Generator/Manual.md
    
    - 307 Dual Analogue State Variable Filters:
      - Overview: Eurorack/307-Dual-Analogue-State-Variable-Filters/index.md
      - Manual: Eurorack/307-Dual-Analogue-State-Variable-Filters/Manual.md
    
    - 308 Voltage Controlled Filter & Wavefolder:
      - Overview: Eurorack/308-Voltage-Controlled-Filter-And-Wavefolder/index.md
      - Manual: Eurorack/308-Voltage-Controlled-Filter-And-Wavefolder/Manual.md
    
    - 309 Advanced Clock Source:
      - Overview: Eurorack/309-Advanced-Clock-Source/index.md
      - Manual: Eurorack/309-Advanced-Clock-Source/Manual.md

  - Archive:

    - Index: archive/index.md

    - VCF-1:
      - Overview: archive/VCF-1/index.md
      - Manual: archive/VCF-1/Manual.md
      
    - VCF-2 (1U):
      - Overview: archive/VCF-2/index.md
      - Manual: archive/VCF-2/Manual.md
    
    - Luther's VCO:
      - Overview: archive/Luthers-VCO/index.md
      - Manual: archive/Luthers-VCO/Manual.md
    
    - 1VOct Calibrator:
      - Overview: archive/1VOct-Calibrator/index.md
      - Manual: archive/1VOct-Calibrator/Manual.md
    
    - Big Button Pico:
      - Overview: archive/Big-Button-Pico/index.md
      - Manual: archive/Big-Button-Pico/Manual.md
    
    - Micro S&H:
      - Overview: archive/uS&H/index.md
      - Manual: archive/uS&H/Manual.md

    - VCA Duck:
      - Overview: archive/VCA-Duck/index.md
      - Manual: archive/VCA-Duck/Manual.md
    
    - Faderbanks:
      - Overview: archive/Faderbanks/index.md
      - Manual: archive/Faderbanks/Manual.md
  
  - Standalone:

    - Dronebox-1:
      - Overview: Standalone/Dronebox-1/index.md
      - Manual: Standalone/Dronebox-1/Manual.md
    
    - Percbox:
      - Overview: Standalone/Percbox/index.md
      - Manual: Standalone/Percbox/Manual.md
    
    - Synthcard:
      - Overview: Standalone/Synthcard/index.md
      - Manual: Standalone/Synthecard/Manual.md

theme: 
  name: readthedocs

copyright: 'Â© 2026 F113X'